### ISSUE TITLE
Timestamp on image bands

### ISSUE THREAD

**Issue by DShoemate** [sinergise/sentinelhub#1]
The path to image files specified in MTD_MS1L1C.xml seems to be based on the datatake_sensing_start rather than the timestamp found in tileInfo.json. If the timestamp is used to name the files, the images can't open correctly in SNAP.

e.g. : 
Path in MTD_MS1L1C.xml = GRANULE/L1C_T15RUQ_A009218_20170328T170619/IMG_DATA/T15RUQ_20170328T170301_B01
Downloaded path based on timestamp = GRANULE\L1C_T15RUQ_A009218_20170328T170619\IMG_DATA\T15RUQ_20170328T170619_B01

**Comment by AleksMat** [comment]
You are right, we used the wrong timestamp for naming image files. We have just uploaded the new version and the problem should be fixed.

Thank you for letting us know about the issue. If you find anything else or have some comments about the script, we will be happy to hear them.
