### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by Fernerkundung** [sinergise/sentinelhub#11]
Do you plan on adding a license to this project?

Currently it is without license and as such I am not sure where/how I can use this tool. Effectively I can't use or include it at all without asking your specific permission for each case.

**Comment by AleksMat** [comment]
We have just added the open MIT license: [LICENSE.md](https://github.com/sinergise/sentinelhub/blob/master/LICENSE.md)

Thank you for reminding us about that.
