### ISSUE TITLE
Unable to import and run download_safe_format

### ISSUE THREAD

**Issue by attibalazs** [sinergise/sentinelhub#2]
Hi, 

I am unable to import and run the download_safe_format function.

I have installed sentinelhub through pip.

```
import sentinelhub


def main():

    print('starting to download satellite data')
    res = sentinelhub.download_safe_format(tile=('T38TML', '2015-12-19'), entire_product=True)
    print('Finished downloading satellite data')

if __name__ == '__main__':
    main()
```

>     res = sentinelhub.download_safe_format(tile=('T38TML', '2015-12-19'), entire_product=True)
> AttributeError: 'module' object has no attribute 'download_safe_format'

It works when i do it in the python console as suggested in your Readme file.

I also tried importing the functions like this, but it still doesn't work

>     from sentinelhub import download_safe_format, get_safe_format, download_data
> ImportError: cannot import name download_safe_format

Thanks

**Comment by AleksMat** [comment]
Hello,

I retried importing functions from the module and everything seems to work. So I think the problem might be on your side. Here are some things you might want to try:

- Make sure that you don't have a file named ```sentinelhub.py``` in your working directory.
- You can check attributes of imported module by adding the following line in your script
```
print(dir(sentinelhub))
```
it should return 
```
['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', 'aws', 'download', 'download_data', 'download_safe_format', 'get_safe_format']
```
- Your python development tool might be using different version of python than your console. Therefore check that the module is correctly installed in both versions.

- Worst case: you can take only files ```aws.py``` and ```download.py``` from the module and copy them to your working directory. Then you can import ```download_safe_format``` function with
```
from aws import download_safe_format
```

**Comment by attibalazs** [comment]
Thanks for the quick reply and for putting this project together.
You are right I made a rookie mistake i called the file **snippets/sentinelhub.py**, not the first time i do this with a new library I'm playing with. 

Thanks again
