### ISSUE TITLE
Is there a way to filter by cloud cover ?

### ISSUE THREAD

**Issue by attibalazs** [sinergise/sentinelhub#4]
I'm looking through your functions, is there a way to filter by cloud cover ?
Trying to get the latest tile with cloud cover between 0-5%

Thank you

**Comment by gmilcinski** [comment]
No, not yet. You are welcome to contribute to this project.

**Comment by attibalazs** [comment]
thanks for the quick response, i'll let you know if i figure it out :)

**Comment by attibalazs** [comment]
Any hints on where I should look, how this could fit into the project ?

**Comment by gmilcinski** [comment]
Thinking about it.. perhaps it would be worth to wait a few weeks as we will most probably establish an OpenSearch interface, which one will be able to query to get information about the catalogue. I cannot state exactly, when this will happen as it does not depend solely on us, but should be soon.

Until that moment, the only option is to crawl all possible dates within specific tile and check tileInfo.json file, which includes information about meta-data.

**Comment by attibalazs** [comment]
Thanks, I will look into it and see if i can do something.

**Comment by AleksMat** [comment]
Hi attibalazs,
I think it would be possible to add cloud cover filter to current script with not much work. I suggest the following:
- cloud cover can be obtained from ```tileInfo.js``` files (attribute cloudyPixelPercentage)
- Class ```SafeTile()``` in ```aws.py``` file already collects ```tileInfo.js``` file and stores it into ```self.tile_info```. There you can extract the cloud cover percentage.
- In the beginning of ```get_structure()``` method of ```SafeTile()``` class you can add condition to return empty dict if cloud cover percentage is to high. This way script will only download tiles with specified max cloud percentage. 
- the rest should be easy ...

Feel free to make any contributions to project. :)

**Comment by attibalazs** [comment]
@AleksMat thanks for your comment, I just saw it, my approach is a bit cruder, I'll try to refine it using your suggestion. This is what I have so far, I didn't need to change your library with this approach.

```
def get_sentinel2_data(tile, data_folder, cloud_cover_max):

    # initalize tile
    safe_tile = SafeTile(tile_name=tile[0], date=tile[1])

    # get cloud cover percentage
    tile_info = safe_tile.get_tile_info()
    cloud_cover = tile_info['cloudyPixelPercentage']

    # check if is below the limit
    if cloud_cover <= cloud_cover_max:
        sentinelhub.download_safe_format(tile=tile, entire_product=True, folder=data_folder)
    else:
        logging.warning('cloud cover is {0} which exceeds the acceptable value of {1}'.format(cloud_cover, cloud_cover_max))
```

**Comment by AleksMat** [comment]
Thank you, we hope it will be useful for other users as well.
