### ISSUE TITLE
Latest available tile

### ISSUE THREAD

**Issue by haydew** [sinergise/sentinelhub#6]
I raised an issues yesterday in regards to finding the most recent tile in sync sentinelhub. 
Im not to proud of my coding skills so hence the location of posting this and not commiting.
I have managed to sort a way to find the latest available bands by tile and download using sentinelhub.download_data. (Band 4 and 8)
Here is a copy of the code.

**Comment by haydew** [comment]
[awsTileSearch.txt](https://github.com/sinergise/sentinelhub/files/1126830/awsTileSearch.txt)

**Comment by haydew** [comment]
for the function to opertate, you will need to unhash line 30 downloadSent(dateStructure, filedateStructure)

**Comment by AleksMat** [comment]
Thank you, we hope it will be useful for other users as well.
