### ISSUE TITLE
Single-digit UTM zone issue

### ISSUE THREAD

**Issue by fsteinmetz** [sinergise/sentinelhub#8]
When the UTM zone has a single digit, downloading in SAFE format fails.

```python
import sentinelhub
sentinelhub.download_safe_format(tile=('4WEE', '2017-06-15'))
```
fails with:
```
[...]
DownloadError: Invalid url request http://sentinel-s2-l1c.s3.amazonaws.com/tiles/4W/E/E/2017/6/15/1/tileInfo.json
```

**Comment by AleksMat** [comment]
You are right, it was a bug. Thank you for contribution.

I also added option to specify tile name as ```T04WEE``` or ```04WEE```. 

Updated version is now also on PyPI.
